---
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
  register: fzf_clone

- name: Install fzf
  shell: ~/.fzf/install
  when: fzf_clone.changed

- name: Clone fasd
  git:
    repo: https://github.com/clvv/fasd.git
    dest: ~/.fasd
  register: fasd_clone

- name: Install fasd
  shell: ( cd ~/.fasd ; PREFIX=$HOME/.fasd make install; ) ;
  when: fasd_clone.changed
